---
languageCode: en-us
baseURL: http://adamgallant.ca/
title: Adam Gallant | Audio Engineer / Mixer / Musician
MetaDataFormat: yaml
params:
  AuthorName: Scott Gallant
  GitHubUser: scottgallant
  Subtitle: Some subtitle
permalinks:
  projects: "/year/:filename/"
