---
languageCode: "en-us"
baseURL: "http://adamgallant.ca/"
title: "Adam Gallant | Audio Engineer / Mixer / Musician"
MetaDataFormat: "yaml"
permalinks:
  projects: /year/:filename/
params:
  Subtitle: "Some subtitle"
  AuthorName: "Scott Gallant"
  GitHubUser: "scottgallant"
menu:
  main:
    name: "Home"
    url: "/"
    weight:  "0"
---
