---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
  projects:
    default_front_matter_template: projects
upload_dir: static/forestryio/images
public_path: "/forestryio/images"
front_matter_path: "/forestryio/images"
use_front_matter_path: false
file_template: ":filename:"
version: '0.19'
