---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- path: content/projects
  label: Projects
  create: all
  templates:
  - projects
  default_front_matter_template: projects
- path: content
  label: Pages
  create: all
  hidden: true
upload_dir: static/forestryio/images
public_path: "/forestryio/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.19'
