---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: data/home.toml
  label: Homepage
- type: directory
  path: content/projects
  label: Year
  create: documents
  match: "**/*"
  templates:
  - projects
upload_dir: static/forestryio/images
public_path: "/forestryio/images"
front_matter_path: "/forestryio/images"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.19
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.19'
