---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  hidden: true
upload_dir: static/forestryio/images
public_path: "/forestryio/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.19
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.19
  preview_output_directory: public
  output_directory: public
version: '0.19'
